### ISSUE TITLE
Volume slider

### ISSUE THREAD

**Issue by faduchesne** [nldroid/rotel_esphome#1]
Hi ! Is it possible to add the vol_nn! command to set the volume trough Home assistant. Thx for your help.

**Comment by nldroid** [comment]
Hi. I tried but i couldn't get it to work. This esphome code almost works but i don't know how to get the volume value in the nn

```
number:
  - platform: template
    name: "Volume"
    min_value: 1
    max_value: 50
    id: volume_set
    step: 1
    set_action:
      then:
        - uart.write: "vol_nn!"
```

I created some buttons for myself with some fixed values:

```
  - platform: template
    name: "Set volume to 15"
    icon: "mdi:fast-forward-15"
    on_press:
      - uart.write: "vol_15!"
```

Hope this helps.
